# -*- coding: utf-8 -*-
"""PROJECT_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dw1CCITFbgzy4Fd-3rJWglmmotw0OG16
"""

import pandas as pd

dataset = pd.read_csv("diabities.csv")

dataset.head(10)

dataset.info()

dataset.isnull().sum()

x=dataset.iloc[: ,: -1]
y=dataset.iloc[: ,-1]

x

y

from sklearn.model_selection import train_test_split
x_train, x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=6,criterion= 'entropy')
classifier.fit(x_train,y_train)
y_pred=classifier.predict(x_test)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)
acc2=round(accuracy_score(y_test,y_pred),2)*100
acc2

from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(solver ='lbfgs',max_iter=1000)
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
accuracy_score(y_test,y_pred)

from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
round(accuracy_score(y_test,y_pred),2)*100